from __future__ import annotations

from app.domain.context import fetch_user_settings
from app.domain.llm import is_ollama_target, resolve_llm_target
from app.domain.ollama.defaults import OLLAMA_NUM_CTX as _OLLAMA_NUM_CTX

from .assemble import (
    _FENCE_RE,
    _assemble_manifest,
    _code_step_tests_executable,
    _infer_fence_language,
    _infer_python_entrypoint,
    _looks_like_python,
    _looks_like_sql,
    _repair_code_fences,
    _repair_manifest_shapes,
    _retarget_code_fences,
)
from .constants import (
    _BAND_ANALYZE,
    _BAND_ANALYZE_SOLO,
    _BAND_ASSEMBLE,
    _BAND_ASSEMBLE_SOLO,
    _BAND_CODE,
    _BAND_CODE_SOLO,
    _BAND_CONSISTENCY,
    _BAND_POLISH,
    _BAND_POLISH_SOLO,
    _BAND_QUIZZES,
    _BAND_QUIZZES_SOLO,
    _BAND_THEORY,
    _BAND_THEORY_SOLO,
    _MAX_ARTICLE_FOR_PROMPT,
    _MAX_CHAPTERS,
    _THEORY_PARALLEL_LIMIT,
    _THEORY_SERIAL_PREFIX,
)
from .messages import (
    _analyze_user_message,
    _code_user_message,
    _consistency_user_message,
    _polish_user_message,
    _quizzes_user_message,
    _task_user_message,
    _theory_user_message,
)
from .normalize import (
    _normalize_book_spine,
    _normalize_chapters,
    _normalize_code_tasks,
    _normalize_deviations,
    _normalize_domain,
    _normalize_open_tasks,
    _normalize_quizzes,
    _normalize_theory_step,
)
from .pipeline import (
    generate_course_from_article,
    iter_course_from_article,
    stream_course_from_article,
)
from .polish import (
    _apply_book_polish_edits,
    _apply_opening_edit,
    _chapter_opening,
    _iter_book_polish,
    _polish_full_content_ok,
)
from .progress import _band_progress, _parse_json_object, _sse_event, _stage_event, _stage_json
from .stages import (
    _iter_code_stage,
    _iter_practice_stage,
    _iter_quizzes_and_code_parallel,
    _iter_quizzes_stage,
    _iter_task_stage,
)
from .textutil import (
    _articles_from_body,
    _as_str,
    _combined_corpus,
    _excerpt_balanced,
    _join_string_list,
    _slug,
    _string_list,
    _video_steps_from_sources,
)
from .theory import (
    _await_indexed,
    _expand_one_theory_chapter,
    _iter_theory_expansion,
    _theory_parallel_limit,
    _theory_serial_count,
)

__all__ = [
    "generate_course_from_article",
    "stream_course_from_article",
    "iter_course_from_article",
    "fetch_user_settings",
    "is_ollama_target",
    "resolve_llm_target",
    "_assemble_manifest",
    "_code_step_tests_executable",
    "_FENCE_RE",
    "_infer_fence_language",
    "_infer_python_entrypoint",
    "_looks_like_python",
    "_looks_like_sql",
    "_repair_code_fences",
    "_repair_manifest_shapes",
    "_retarget_code_fences",
    "_BAND_ANALYZE",
    "_BAND_ANALYZE_SOLO",
    "_BAND_ASSEMBLE",
    "_BAND_ASSEMBLE_SOLO",
    "_BAND_CODE",
    "_BAND_CODE_SOLO",
    "_BAND_CONSISTENCY",
    "_BAND_POLISH",
    "_BAND_POLISH_SOLO",
    "_BAND_QUIZZES",
    "_BAND_QUIZZES_SOLO",
    "_BAND_THEORY",
    "_BAND_THEORY_SOLO",
    "_MAX_ARTICLE_FOR_PROMPT",
    "_MAX_CHAPTERS",
    "_OLLAMA_NUM_CTX",
    "_THEORY_PARALLEL_LIMIT",
    "_THEORY_SERIAL_PREFIX",
    "_analyze_user_message",
    "_code_user_message",
    "_consistency_user_message",
    "_polish_user_message",
    "_quizzes_user_message",
    "_task_user_message",
    "_theory_user_message",
    "_normalize_book_spine",
    "_normalize_chapters",
    "_normalize_code_tasks",
    "_normalize_deviations",
    "_normalize_domain",
    "_normalize_open_tasks",
    "_normalize_quizzes",
    "_normalize_theory_step",
    "_apply_book_polish_edits",
    "_apply_opening_edit",
    "_chapter_opening",
    "_iter_book_polish",
    "_polish_full_content_ok",
    "_band_progress",
    "_parse_json_object",
    "_sse_event",
    "_stage_event",
    "_stage_json",
    "_iter_code_stage",
    "_iter_practice_stage",
    "_iter_quizzes_and_code_parallel",
    "_iter_quizzes_stage",
    "_iter_task_stage",
    "_articles_from_body",
    "_as_str",
    "_combined_corpus",
    "_excerpt_balanced",
    "_join_string_list",
    "_slug",
    "_string_list",
    "_video_steps_from_sources",
    "_await_indexed",
    "_expand_one_theory_chapter",
    "_iter_theory_expansion",
    "_theory_parallel_limit",
    "_theory_serial_count",
]
